name: 'Code Coverage Cobertura' 
author: 'Ketan <limbasiyaketan@gmail.com>'
description: 'A GitHub Action that reads Cobertura format code coverage files and outputs a text or markdown summary.'
branding:
  icon: book-open
  color: purple
inputs:
  files:
    description: 'Code coverage files to analyse and compare. Please enter your files comma separated. First file should be Base file. Ex. BaseBranchCoverage.xml,CurrentBranchCoverage.xml'
    required: true
  allow_coverage_diff:
    description: 'Input allowed coverage difference between two branches in %.'
    required: false
    default: -0.1
  badge:
    description: 'Include a badge in the output - true / false (default).'
    required: false
    default: 'false'
  format:
    description: 'Output Format - markdown or text (default).'
    required: false
    default: 'text'
  output:
    description: 'Output Type - console (default), file or both.'
    required: false
    default: 'console'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.files }}
    - '--allow_coverage_diff'
    - ${{ inputs.allow_coverage_diff }}
    - '--badge'
    - ${{ inputs.badge }}
    - '--format'
    - ${{ inputs.format }}
    - '--output'
    - ${{ inputs.output }}
